### PR TITLE
Pass scene as a parameter so we can construct multiple scenes

### PR DESCRIPTION
**Pull request by white0ut**
Removes usage of `getApp().scene` in lieu of passing scene as a parameter. The magic is in `initFirstScene()` where the initialized scene gets swapped out with the battleScene.

Then we can construct new scenes, attach them, etc..

Hopefully I didn't break anything ;)

[screen-capture.webm](https://github.com/dudasaus/babylonjs-cards/assets/6537255/698ec19b-86f3-4523-9290-b73297a7cc85)

### CODE REVIEW

**Comment by white0ut** [comment]
DO_NOT_SUBMIT: texture helper is broken, and I have no clue why right now :)

**Comment by dudasaus** [comment]
LGTM

I was thinking about this some more- global vars are bad, but some dependency injection within a context (like a battle) can still make our life much better. We know certain things- one battle will exist at a time, a battle will always have a scene, a specific GUI, and some other parts we likely want many "child components" of the battle to have easy access to. We may still pivot from specifically passing around scene to every constructor in the future

**Review by dudasaus — APPROVED** [review]

**Comment by dudasaus** [comment]
Also whatever emoji font you have (Windows 12?) looks way cooler than mine

**Comment by white0ut** [comment]
uh oh you merged this, just beware that the texture helper is currently broken haha

Something or another about the card needing to be initialized. Headed to the gym right now but will take a look in a bit

**Pull request merged**
